export const LOAD_CHARACTERS = "LOAD_CHARACTERS";
export const LOAD_CHARACTERS_SUCCESS = "LOAD_CHARACTERS_SUCCESS";
export const LOAD_CHARACTERS_ERROR = "LOAD_CHARACTERS_ERROR";
export const LOAD_CHARACTER_ITEM  = "LOAD_CHARACTER_ITEM";
export const LOAD_CHARACTER_ITEM_SUCCESS = "LOAD_CHARACTER_ITEM_SUCCESS";
export const LOAD_CHARACTER_ITEM_ERROR = "LOAD_CHARACTER_ITEM_ERROR";